### ISSUE TITLE
What's with the limitation of imported meshes only? 

### ISSUE THREAD

**Issue by TheRealFame** [bikemurt/godot-vertex-painter#1]
Read the subject! I been wanting to use a plane mesh for this

**Comment by Radivarig** [comment]
Readme says that the mesh needs to have clear_surfaces() method.
> Only imported meshes will work (or ArrayMesh, which have a clear_surfaces() method)

**Comment by bikemurt** [comment]
As referenced in the main docs, we need a `clear_surfaces` method on the mesh in order to use the `MeshDataTool` properly. The primitive shapes do not have that method.

https://github.com/bikemurt/godot-vertex-painter/blob/08851d0c5f54cb358fc4bb1666a3fa6ef6f7587a/addons/vertex_painter/v2/vertex_painter_3d.gd#L182

**Comment by TheRealFame** [comment]
So it's viable to just instance an glb plane mesh on my scene everytime I know I'm gonna vertex paint a mesh?

**Comment by bikemurt** [comment]
Yup, that would work fine since it's an `ArrayMesh`

**Comment by TheRealFame** [comment]
> So it's viable to just instance an glb plane mesh on my scene everytime I know I'm gonna vertex paint a mesh?

It was not for anyone wanting to know. I've since then decided to try tackling the map in blender.

**Comment by Radivarig** [comment]
@bikemurt is there a way this can be worked around through code to allow painting on any MeshInstance3D.mesh?
From what I understand the surface in Godot is like a submesh, and the `clear_surfaces` method seems to delete them so I'm under the impression that the same can be achieved differently for mesh that do not have that method available.
Can you please describe why `clear_surfaces` is needed in the first place?

**Comment by Radivarig** [comment]
@bikemurt any comment? It would be a large usability improvement.

**Comment by bikemurt** [comment]
Hi @Radivarig . `clear_surfaces()` is required every time the mesh is painted, because the `MeshDataTool` has to commit new mesh data on each update. To my knowledge there is no other way to modify mesh data at runtime, so this limitation will be present as long as the `MeshDataTool` is required to be used.

Unfortunately I don't have time to work on this anymore, but if someone else wants to try to tackle fixing it, or a workaround for the primitive Godot meshes, they certainly can.
